### ISSUE TITLE
In WvW, some structure says "flipped 7 h ago" when it was like 10 minutes

### ISSUE THREAD

**Issue by takosalad** [Snappey/maps.gw2.io#1]
It seems some structures show incorrect owner from many hours in the past.
Is it a problem with ArenaNet's API?

Also, I saw there is some box to enter an API key, what is it actually important for/different, than using the maps w/o API key?

Edit: Both questions are also posed here
https://en-forum.guildwars2.com/topic/51896-wvw-api/
(and it seems the API key isn't important for refresh issues, just for viewing personal account-specific API things).
Someone wrote his findings there too, quote

"t's a server team(world) related issue.example : a server team could be affected in a Matchup A but not another server team in a Matchup B

It's not related to MCM population server because i have tested on poor D5 server with nothing on the map except 20 roamers ^"

**Comment by Snappey** [comment]
Yeah I believe its the endpoints that return inconsistent data, noticed it a bit during development. Will go through phases of being accurate and up to date then data will freeze at a given state for seemingly random intervals.

Not much I can do on my side as far as I can think.

API Key wise you don't need to use it if you're just using the WvW aspect, the main use case is a live marker feature through Blish HUD that allows you to see you and your friends position on the map. From what I can remember it might also be used in the half baked wizard vault listing as well.
