### ISSUE TITLE
Missing Core Tyria Mastery Insights

### ISSUE THREAD

**Issue by E-Gantz** [Snappey/maps.gw2.io#4]
These 3 mastery insights seem to be missing from the map
https://wiki.guildwars2.com/wiki/Iron_Marches_Insight:_Sunken_Halls_of_Clarent
https://wiki.guildwars2.com/wiki/Mount_Maelstrom_Insight:_Volcanic_Rim
https://wiki.guildwars2.com/wiki/Timberline_Falls_Insight:_Copperhammer_Mines

**Comment by Snappey** [comment]
Thanks much appreciated, I'll hopefully get around to adding them manually later this week.
